<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.2
 */

/**
 * Database `rudrivtg_constr_loc`
 */

/* `rudrivtg_constr_loc`.`kso` */
$kso = array(
  array('id' => '1','template' => 'КСО', 'type' => 'КСО-366','name' => 'Камера серии КСО-366 (разъединитель РВЗ-10/630-I У3. 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2200х800х1200 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '131','price_rub' => '','price' => '1005','block_id' => '7','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '773','delivery' => '0'),
  array('id' => '2','template' => 'КСО', 'type' => 'КСО-366','name' => 'Камера серии КСО-366 (разъединитель РВЗ-10/630-II У3. 2 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2200х1100х1200 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '132','price_rub' => '','price' => '1939','block_id' => '8','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '1492','delivery' => '0'),
  array('id' => '3','template' => 'КСО', 'type' => 'КСО-366','name' => 'Камера серии КСО-366 (разъединитель РВЗ-10/630-II У3. 3 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2200х1100х1200 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '133','price_rub' => '','price' => '2619','block_id' => '9','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '2015','delivery' => '0'),
  array('id' => '4','template' => 'КСО', 'type' => 'КСО-366','name' => 'Камера серии КСО-366 (разъединитель РВЗ-10/630-II У3. 2 шт.,РВ-10/630 У3. 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2200х1100х1200 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '143','price_rub' => '','price' => '2619','block_id' => '12','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '2015','delivery' => '0'),
  array('id' => '5','template' => 'КСО', 'type' => 'КСО-366м-UVC','name' => 'Камера серии КСО-366м-UVC (разъединитель РВ-10/630 У3. 1 шт., контактор ваккумный UVC 7,2кВ, 400А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х750х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '111','price_rub' => '0','price' => '4032','block_id' => '1','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '3102','delivery' => '0'),
  array('id' => '6','template' => 'КСО', 'type' => 'КСО-366м-UVC','name' => 'Камера серии КСО-366м-UVC (разъединитель РВ-10/630 У3. 2 шт., контактор ваккумный UVC 7,2кВ, 400А 2 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х1065х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '112','price_rub' => '','price' => '8313','block_id' => '2','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '6394','delivery' => '0'),
  array('id' => '7','template' => 'КСО', 'type' => 'КСО-366м-UVC','name' => 'Камера серии КСО-366м-UVC (разъединитель РВ-10/630 У3. 3 шт., контактор ваккумный UVC 7,2кВ, 400А 3 шт.).  Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х2130х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '113','price_rub' => '0','price' => '12592','block_id' => '3','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '9686','delivery' => '0'),
  array('id' => '8','template' => 'КСО', 'type' => '2. КСО НА ВЫКАТНЫХ КОНТАКТОРАХ','name' => 'КСО на 1 двигатель','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '121','price_rub' => '0','price' => '0','block_id' => '4','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '9','template' => 'КСО', 'type' => '2. КСО НА ВЫКАТНЫХ КОНТАКТОРАХ','name' => 'КСО на 2 двигателя','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '122','price_rub' => '0','price' => '0','block_id' => '5','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '10','template' => 'КСО', 'type' => '2. КСО НА ВЫКАТНЫХ КОНТАКТОРАХ','name' => 'КСО на 3 двигателя','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '123','price_rub' => '0','price' => '0','block_id' => '6','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '11','template' => 'КСО', 'type' => '4. КСО БАЙПАСА ПЧ','name' => 'КСО на контакторах/ выключателях','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '141','price_rub' => '0','price' => '0','block_id' => '10','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '12','template' => 'КСО', 'type' => '4. КСО БАЙПАСА ПЧ','name' => 'КСО на выкатных контакторах/ выключателях','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '142','price_rub' => '0','price' => '0','block_id' => '11','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '14','template' => 'КСО', 'type' => '1. ЯЧЕЙКА ПИТАНИЯ','name' => 'Ячейка питания (один вывод)','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '211','price_rub' => '0','price' => '0','block_id' => '13','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '15','template' => 'КСО', 'type' => '1. ЯЧЕЙКА ПИТАНИЯ','name' => 'Ячейка питания (два вывода)','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '211W','price_rub' => '0','price' => '0','block_id' => '14','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '16','template' => 'КСО', 'type' => 'КСО-366Mv-11-630(ТН)','name' => 'Камера КСО с измерительным трансформатором напряжения. (разъединитель РВЗ-10/630-II У3, трансформатор ЭНОЛ-ЭК-6, предохранитель ПН01-10 У3, или аналоги). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х800х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '221','price_rub' => '0','price' => '2275','block_id' => '15','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '1750','delivery' => '0'),
  array('id' => '17','template' => 'КСО', 'type' => '1. ПРЕОБРАЗОВАТЕЛЬ ЧАСТОТЫ','name' => 'Секция реактора с байпасом','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '312','price_rub' => '0','price' => '0','block_id' => '17','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '18','template' => 'КСО', 'type' => '1. ПРЕОБРАЗОВАТЕЛЬ ЧАСТОТЫ','name' => 'Секция реактора ','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '313','price_rub' => '0','price' => '0','block_id' => '18','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '19','template' => 'КСО', 'type' => '2. ЭЛЕКТРОДВИГАТЕЛЬ','name' => 'Асинхронный электродвигатель','article' => '','manufacturer' => 'Заказчик','dimension_draw' => '','scheme_number' => '321','price_rub' => '0','price' => '0','block_id' => '19','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '20','template' => 'КСО', 'type' => '2. ЭЛЕКТРОДВИГАТЕЛЬ','name' => 'Синхронный электродвигатель','article' => '','manufacturer' => 'Заказчик','dimension_draw' => '','scheme_number' => '322','price_rub' => '0','price' => '0','block_id' => '20','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '21','template' => 'КСО', 'type' => 'Секция ввода','name' => 'Секция ввода. Степень защиты: IP21  Габариты (ВхШхГ): 2300х400х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '41','price_rub' => '0','price' => '245','block_id' => '21','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '190','delivery' => '0'),
  array('id' => '22','template' => 'КСО', 'type' => 'КСО-366м-UVC','name' => 'Камера серии КСО-366м-UVC (контактор ваккумный UVC 7,2кВ, 400А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х750х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '42','price_rub' => '0','price' => '3738','block_id' => '22','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '2875','delivery' => '0'),
  array('id' => '23','template' => 'КСО', 'type' => 'КСО-366м-UVC','name' => 'Камера серии КСО-366м-UVC (разъединитель РВ-10/630 У3. 1 шт., контактор ваккумный UVC 7,2кВ, 400А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х750х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '43','price_rub' => '0','price' => '4033','block_id' => '23','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '3102','delivery' => '0'),
  array('id' => '24','template' => 'КСО', 'type' => 'КСО-366м-UVC','name' => 'Секция выкатного контактора','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '44','price_rub' => '0','price' => '0','block_id' => '24','text_type' => 'KM','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '25','template' => 'КСО', 'type' => 'КСО-366','name' => 'Камера серии КСО-366 (разъединитель РВЗ-10/630-I У3. 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2200х800х1200 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '45','price_rub' => '0','price' => '1005','block_id' => '25','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '773','delivery' => '0'),
  array('id' => '27','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(разъединитель РВ-10/630 У3. 1 шт., выключатель ваккумный BBTEL 630А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х800х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '111','price_rub' => '0','price' => '5318','block_id' => '1','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '4091','delivery' => '0'),
  array('id' => '28','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(разъединитель РВ-10/630 У3. 2 шт., выключатель ваккумный BBTEL 630А 2 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х2000х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '112','price_rub' => '0','price' => '10901','block_id' => '2','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '8386','delivery' => '0'),
  array('id' => '29','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(разъединитель РВ-10/630 У3. 3 шт., выключатель ваккумный BBTEL 630А 3 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х2800х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '113','price_rub' => '0','price' => '16032','block_id' => '3','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '12333','delivery' => '0'),
  array('id' => '30','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(выкатной выключатель ваккумный BBTEL 630А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х1200х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '121','price_rub' => '0','price' => '7787','block_id' => '4','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '5990','delivery' => '0'),
  array('id' => '31','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(выкатной выключатель ваккумный BBTEL 630А 2 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х2000х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '122','price_rub' => '0','price' => '15314','block_id' => '5','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '11780','delivery' => '0'),
  array('id' => '32','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(выкатной выключатель ваккумный BBTEL 630А 3 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х2800х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '123','price_rub' => '0','price' => '22838','block_id' => '6','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '17568','delivery' => '0'),
  array('id' => '33','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL(выключатель ваккумный BBTEL 630А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х800х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '42','price_rub' => '0','price' => '4925','block_id' => '22','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '3788','delivery' => '0'),
  array('id' => '34','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(разъединитель РВ-10/630 У3. 1 шт., выключатель ваккумный BBTEL 630А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х800х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '43','price_rub' => '0','price' => '5318','block_id' => '23','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '4091','delivery' => '0'),
  array('id' => '35','template' => 'КСО', 'type' => 'КСО-366м-BBTEL','name' => 'Камера серии КСО-366м-BBTEL.(выкатной выключатель ваккумный BBTEL 630А 1 шт.). Без ТТ и РЗА. Степень защиты: IP21  Габариты (ВхШхГ): 2300х1200х1100 мм.','article' => '','manufacturer' => 'КЭП','dimension_draw' => '','scheme_number' => '44','price_rub' => '0','price' => '7787','block_id' => '24','text_type' => 'Q','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '5990','delivery' => '0'),
  array('id' => '36','template' => 'КСО', 'type' => '4. СТАНДАРТНЫЕ БЛОКИ','name' => 'Устройство плавного пуска','article' => '','manufacturer' => 'ООО «Завод Ру-Драйв»','dimension_draw' => '','scheme_number' => 'upp','price_rub' => '0','price' => '0','block_id' => '28','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '37','template' => 'КСО', 'type' => '4. СТАНДАРТНЫЕ БЛОКИ','name' => 'Устройство плавного пуска','article' => '','manufacturer' => 'ООО НПП «РУ-Инжиниринг»','dimension_draw' => '','scheme_number' => 'upp','price_rub' => '0','price' => '0','block_id' => '28','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '38','template' => 'КСО', 'type' => '1. ПРЕОБРАЗОВАТЕЛЬ ЧАСТОТЫ','name' => 'Преобразователь частоты','article' => '','manufacturer' => 'ООО НПП «РУ-Инжиниринг»','dimension_draw' => '','scheme_number' => '312','price_rub' => '0','price' => '0','block_id' => '16','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0'),
  array('id' => '39','template' => 'КСО', 'type' => '1. ПРЕОБРАЗОВАТЕЛЬ ЧАСТОТЫ','name' => 'Преобразователь частоты','article' => '','manufacturer' => 'ООО «Завод Ру-Драйв»','dimension_draw' => '','scheme_number' => '312','price_rub' => '0','price' => '0','block_id' => '16','text_type' => '','PO' => '0','KD' => '0','assembly' => '0','mounting' => '0','montage' => '0','PNR' => '0','cost' => '0','delivery' => '0')
);
